# Assign PR to Author
# https://github.com/samspills/assign-pr-to-author

name: AutoAssigner
on: [pull_request]

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    steps:
    
    - name: Harden Runner
      uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443

    - uses: samspills/assign-pr-to-author@b313feb250ff414d3aff26525b986f080ee7bd7a
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
