name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/EDlib.sln
    - name: Build
      run: dotnet build src/EDlib.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/EDlib.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: test-coverage-report
        path: coverage/**/coverage.cobertura.xml
