name: CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo in the console output
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry to Microsoft

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read        # for actions/checkout
      pull-requests: write  # for marocchino/sticky-pull-request-comment
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    
    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          api.nuget.org:443
          api.taranissoftware.com:443
          dotnetbuilds.azureedge.net:443
          dotnetcli.azureedge.net:443
          dotnetcli.blob.core.windows.net:443
          github.com:443
          httpbin.org:443
          inara.cz:443
          pipelines.actions.githubusercontent.com:443
          www.edsm.net:443

    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore src/EDlib.sln

    - name: Add User Secrets # used by demo app
      uses: microsoft/variable-substitution@6287962da9e5b6e68778dc51e840caa03ca84495
      with:
        files: 'src/EDlibDemo/appsettings.json'
      env:
        Inara-AppName:  ${{ secrets.INARA_APPNAME }}
        Inara-AppVersion: ${{ secrets.INARA_APPVERSION }}
        Inara-ApiKey:  ${{ secrets.INARA_APIKEY }}
        Inara-IsDeveloped: ${{ secrets.INARA_ISDEVELOPED }}

    - name: Build EDlib
      run: dotnet build src/EDlib.sln --configuration Release --no-restore

    - name: Test EDlib
      run: dotnet test src/EDlib.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        format: 'md'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@fcf6fe9e4a0409cd9316a5011435be0f3327f1e1
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: test-coverage-report
        path: code-coverage-results.md

    - name: Upload EDlib Artifact
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: ci-nuget
        path: src/EDlib/bin/Release/Taranis.Software.EDlib*.nupkg

    - name: Run EDlib Demo
      run: dotnet src/EDlibDemo/bin/Release/net6.0/EDlibDemo.dll
