name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore Dependencies
      run: dotnet restore src/EDlib.sln

    - name: Add User Secrets
      uses: microsoft/variable-substitution@v1
      with:
        files: 'src/UnitTests/appsettings.json, src/EDlibDemo/appsettings.json'
      env:
        Inara-AppName:  ${{ secrets.INARA_APPNAME }}
        Inara-AppVersion: ${{ secrets.INARA_APPVERSION }}
        Inara-ApiKey:  ${{ secrets.INARA_APIKEY }}
        Inara-UserApiKey: ${{ secrets.INARA_USERAPIKEY }}
        Inara-IsDeveloped: ${{ secrets.INARA_ISDEVELOPED }}

    - name: Build EDlib
      run: dotnet build src/EDlib.sln --configuration Release --no-restore

    - name: Test EDlib
      run: dotnet test src/EDlib.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Copy Coverage To Predictable Location
      run: cp coverage/**/coverage.cobertura.xml coverage/coverage.cobertura.xml

    - name: Code Coverage Summary Report
      uses:  irongut/CodeCoverageSummary@v1.0.1
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        format: 'md'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: test-coverage-report
        path: coverage/coverage.cobertura.xml

    - name: Upload Coverage Summary Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: test-coverage-report
        path: code-coverage-results.md

    - name: Upload EDlib Nuget Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: ci-nugets
        path: src/EDlib/bin/Release/Taranis.Software.EDlib*.nupkg

    - name: Upload EDlib.Mock Nuget Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: ci-nugets
        path: src/EDlib.Mock/bin/Release/Taranis.Software.EDlib*.nupkg

    - name: Run EDlib Demo
      run: dotnet src/EDlibDemo/bin/Release/net5.0/EDlibDemo.dll
