# Triages pull requests and applies a label based on paths & files
# modified in the pull request.
#
# This file sets up the workflow (action).
# Create a .github/labeler.yml file with a list of labels and files or 
# folders as minimatch globs to match to the labels. See:
# https://github.com/actions/labeler/blob/master/README.md

name: PRLabeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
