# Triages pull requests and applies a label based on paths & files
# modified in the pull request.
#
# This file sets up the workflow (action).
# Create a .github/labeler.yml file with a list of labels and files or 
# folders as minimatch globs to match to the labels. See:
# https://github.com/actions/labeler/blob/master/README.md

name: PRLabeler
on: 
  pull_request_target:

permissions:
  contents: read

jobs:
  label:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443

    - uses: actions/labeler@5c7539237e04b714afd8ad9b4aed733815b9fab4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
