# Triages pull requests and applies a label based on paths & files
# modified in the pull request.
#
# This file sets up the workflow (action).
# Create a .github/labeler.yml file with a list of labels and files or 
# folders as minimatch globs to match to the labels. See:
# https://github.com/actions/labeler/blob/master/README.md

name: PRLabeler
on: 
  pull_request_target:

permissions:
  contents: read

jobs:
  label:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443

    - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
