name: Build + Deploy

on:
  release:
    types: [published]
    branches: [master]

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience to speed up the build
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  GITHUB_PACKAGE_URL: 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release Build
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: block
        allowed-endpoints: >
          api.nuget.org:443
          dotnetbuilds.azureedge.net:443
          dotnetcli.azureedge.net:443
          dotnetcli.blob.core.windows.net:443
          github.com:443
          httpbin.org:443
          pipelines.actions.githubusercontent.com:443

    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore src/EDlib.sln

    - name: Build EDlib
      run: dotnet build src/EDlib.sln --configuration Release --no-restore

    - name: Test EDlib
      run: dotnet test src/EDlib.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Copy Test Coverage
      run: cp coverage/**/coverage.cobertura.xml coverage/coverage.cobertura.xml

    - name: Generate Test Report
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        format: 'md'
        output: 'both'

    - name: Upload EDlib Artifact
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
      with:
        name: release-nuget
        path: src/EDlib/bin/Release/Taranis.Software.EDlib*.nupkg

    - name: Upload Test Report Artifact
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
      with:
        name: release-nuget
        path: code-coverage-results.md

  deploy-gh:
    name: Deploy to GitHub Packages
    needs: [build]
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          dist.nuget.org:443
          nuget.pkg.github.com:443
          pipelines.actions.githubusercontent.com:443

    - name: Download Artifacts
      uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
      with:
        name: release-nuget

    - name: Setup Nuget
      uses: NuGet/setup-nuget@a21f25cd3998bf370fde17e3f1b4c12c175172f9
      with:
        nuget-version: latest

    - name: Add GitHub package source
      run: nuget sources Add -Name GitHub -Source ${{env.GITHUB_PACKAGE_URL}} -UserName ${{ github.repository_owner }} -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Packages
      run: nuget push **/*.nupkg -source GitHub -SkipDuplicate

    - name: Add Test Report to Release
      uses: irongut/EditRelease@ccf529ad26dddf9996e7dd0f24ca5da4ea507cc2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        id: ${{ github.event.release.id }}
        body: 'Released to GitHub Packages.'
        files: code-coverage-results.md

  deploy-docs:
    name: Deploy Docs
    needs: [build, deploy-gh]
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443

    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - name: Build Documentation
      uses: nikeee/docfx-action@b9c2cf92e3b4aa06878a1410833a8828b4bdcd26
      with:
        args: docfx_project/docfx.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        commit_message: ${{ github.event.head_commit.message }}
