name: Update Docs

on:
  workflow_dispatch:
    branches: [master]

jobs:
  deploy-docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
    
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443

    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - name: Build Documentation
      uses: nikeee/docfx-action@72f9d1a3f38d9f2696a938f29d09921292bf109c
      with:
        args: docfx_project/docfx.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@97fb9635096cfc33bfdc8fc32ef02296dce55ab0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        commit_message: ${{ github.event.head_commit.message }}
